### ISSUE TITLE
lms1xx gazebo depedency

### ISSUE THREAD

**Issue by paulbovbel** [clearpathrobotics/LMS1xx#19]
Was looking through Husky sim recently, agonizing over whether to keep the complete _description and _gazebo separation.

Which led me to realize that if lms1xx is going to provide a URDF with a gazebo tag, it should really propagate the gazebo_plugins dependency. Thoughts @mikepurvis @tonybaltovski?

Would it make sense to provide separate lms1xx_driver and lms1xx_description packages? The nice thing is that existing rosdeps on lmx1xx (if it is redefined as a metapackage), will still pull in all packages, and provide a nice deprecation notice saying that you shouldn't depend on metapackages.

**Comment by mikepurvis** [comment]
I haven't felt that a strict separation is worth the trouble— it's fine IMO for the description to contain extra `<gazebo>` content which has no effect in the real-robot scenario. You definitely wouldn't want a description dependent on `gazebo_plugins`, though, as that would end up adding a lot of unwanted simulation stuff to robot machines.
