### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by sigirvan** [clearpathrobotics/LMS1xx#20]
Hi guys,

I'm new in ROS and i need your help about  connecting LMS111 with ROS.
I already follow the instruction for connecting this device,but I'm still have a problem.

When i run this node using rosrun the error like this appear :

[ INFO] [1440558207.561479097]: Waiting for laser to initialize...
[ERROR] [1440558207.561542850]: accept() on socket [6] failed with error [Too many open files]
[ INFO] [1440558207.562252842]: Waiting for laser to initialize...
[ERROR] [1440558207.562315450]: accept() on socket [6] failed with error [Too many open files]
[ INFO] [1440558207.562370538]: Waiting for laser to initialize...
[ERROR] [1440558207.562431228]: accept() on socket [6] failed with error [Too many open files]

When i open the LMS1xx_node at /my_ws/src/lms1xx/src/LMS1xx_node.cpp and edit this parameter with my parameter in SOPAS, I'm still get error.

//check if laser is fully initialized, else reconnect
      //assuming fully initialized => scaningFrequency=5000
      if (cfg.scaningFrequency != 5000) {
	laser.disconnect();
	ROS_INFO("Waiting for laser to initialize...");
      }

    } while (!laser.isConnected() || cfg.scaningFrequency != 5000);

    if (laser.isConnected()) {
      ROS_INFO("Connected to laser.");

![capture](https://cloud.githubusercontent.com/assets/13960284/9484787/fc2bb326-4bda-11e5-9670-8541e19bf000.PNG)

There some step where i miss ?

Thanks before.

**Comment by watcherZY** [comment]
have you solved this problem?  i meet the same question
