### ISSUE TITLE
Add a parameter for frame in the launch file

### ISSUE THREAD

**Issue by Waterfox** [clearpathrobotics/LMS1xx#27]
The driver appears to always publish to a frame called "laser", regardless of where you attach it in a URDF. Could you consider adding a parameter in the launch file to set the frame. This has confused software using laser data which depends on the TF tree

**Comment by mikepurvis** [comment]
It's already configurable:

https://github.com/clearpathrobotics/LMS1xx/blob/master/src/LMS1xx_node.cpp#L31

This is documented on the ROS Wiki:

http://wiki.ros.org/action/show/LMS1xx?action=show&redirect=lms1xx#Parameters

**Comment by Waterfox** [comment]
Oh shazbot thanks. This one bojangled us.

**Comment by TheDash** [comment]
I think what @Waterfox wanted is, the default launch file for the LMS1xx package does not have a full example of what parameters can be used in the node, and the source code had to be read. 

For non-power users of ROS, it can be hard to know that parameters are defined/provided by a node. Not everyone is comfortable with reading source.

@mikepurvis thoughts on adding
<param name="frame_id" value="laser"/> to the launch for the noobies?

**Comment by mikepurvis** [comment]
Sure, send a PR for it.
