### ISSUE TITLE
Regarding: "$ rosrun lms1xx LMS1xx_node" connection to device failed.

### ISSUE THREAD

**Issue by pantherekaj** [clearpathrobotics/LMS1xx#3]
Hi, i'm unable to connect my device after i execute LMS1xx_node.cpp. I followed exactly what you have done, and change the IP address accordingly. i'm able to ping the IP address. However, it the program only shows the following:
[ INFO] [1412662631.827312965]: Connecting to laser at : 169.254.2.255
[ERROR] [1412662631.829781896]: Connection to device failed (in red)

Can anyone help me to solve this issue? This is very important to the contribution of my project. Thank you.

**Comment by arvinasokan** [comment]
@mikepurvis : Were you able to reconfigure the IP address of the device without using the SOPAS tool?
