### ISSUE TITLE
Quesiton: Code fail to compile in ROS Melodic

### ISSUE THREAD

**Issue by caguero** [clearpathrobotics/LMS1xx#54]
Question: I failed to compile the code in `master` in an Ubuntu Bionic distribution with ROS Melodic because all calls to `logWarn`, `logDebug` failed. Here's an example:

```
In file included from /home/developer/jackal_ws/src/LMS1xx/include/LMS1xx/LMS1xx.h:27:0,
                 from /home/developer/jackal_ws/src/LMS1xx/src/LMS1xx.cpp:36:
/home/developer/jackal_ws/src/LMS1xx/include/LMS1xx/lms_buffer.h: In member function 'void LMSBuffer::readFrom(int)':
/home/developer/jackal_ws/src/LMS1xx/include/LMS1xx/lms_buffer.h:54:7: error: 'logWarn' was not declared in this scope
       logWarn("Buffer read() returned error.");
```

I have a patch that fixes the issue (essentially adding the `CONSOLE_BRIDGE_` prefix to all of them. Do you have any plans for supporting ROS Melodic? Should I just submit a pull request against `master`? Are you considering a separate release branch for Melodic maybe?

**Comment by FahadRazaSJTU** [comment]
Faced the same Error, and fixed it as @caguero said. BTW is there any easy way to it instead of adding prefix in the code?
Thank you.

**Comment by tonybaltovski** [comment]
This has been fixed.
